version: '3'
services:
  postgres:
    restart: always
    image: postgres

  django:
    build:
      context: .
      dockerfile: ./Dockerfile-local
    command: /cs-unplugged/csunplugged/docker-development-entrypoint.sh
    volumes:
      - .:/cs-unplugged
    environment:
      - PORT=8080
      - USE_DOCKER=yes
      - DATABASE_URL=postgres://postgres@postgres:5432/postgres
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: ./infrastructure/nginx/Dockerfile
    volumes:
      - ./csunplugged/:/app/
      - /app/node_modules
    depends_on:
      - django
    ports:
      - "80:80"

  redis:
    build:
      context: .
      dockerfile: ./infrastructure/redis/Dockerfile
    ports:
      - "6379:6379"

  render:
    build:
      context: .
      dockerfile: ./renderservice/Dockerfile-local
      args:
        PROCESS_PORT: 5000
        FLASK_PRODUCTION: 0
        PROJECT_NAME: cs-unplugged-develop
        QUEUE_NAME: render-queue
        API_DISCOVERY_URL: http://queue:5050/api/{api}/{apiVersion}
        STATIC_DIRECTORY: /renderservice/static_mnt
    volumes:
      - ./csunplugged/staticfiles:/renderservice/static_mnt
    ports:
      - "5000:5000"
    depends_on:
      - nginx

  queue:
    build:
      context: .
      dockerfile: ./infrastructure/queue/Dockerfile
      args:
        PROCESS_PORT: 5050
    ports:
      - "5050:5050"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - nginx
      - redis
